name: Build XLibre Debian

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: [ubuntu-24.04, ubuntu-24.04-arm]
    container:
      image: debian:stable
    
    steps:
      - name: Install basic dependencies
        run: |
          apt-get update
          apt-get install -y git git-buildpackage devscripts debhelper build-essential equivs pristine-tar

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure git
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config --global user.email "ci@github.com"
          git config --global user.name "GitHub Actions"

      - name: Build
        run: |
          make

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: debian-packages
          path: build/
          if-no-files-found: warn
